AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  moviesApi

  Sample SAM Template for moviesApi

Globals:
  Function:
    Runtime: java11
    MemorySize: 512
    Timeout: 20


Resources:
  CreateMovieFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: MoviesFunction
      Handler: edu.uchicago.gerber.movies.CreateMovieLambda::handleRequest
      Events:
        PostMovie:
          Type: Api
          Properties:
            Path: /movies
            Method: POST
  ReadMoviesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: MoviesFunction
      Handler: edu.uchicago.gerber.movies.ReadMoviesLambda::handleRequest
      Events:
        PostMovie:
          Type: Api
          Properties:
            Path: /movies
            Method: GET

