AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  moviesApi

  Sample SAM Template for moviesApi

Globals:
  Function:
    Runtime: java11
    MemorySize: 512
    Timeout: 20
    Environment:
      Variables:
        MOVIES_TABLE: !Ref MoviesTable


Resources:
  MoviesTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: String

  CreateMovieFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: MoviesFunction
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref MoviesTable
      Handler: edu.uchicago.gerber.movies.CreateMovieLambda::handleRequest
      Events:
        PostMovie:
          Type: Api
          Properties:
            Path: /movies
            Method: POST
  ReadMoviesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: MoviesFunction
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref MoviesTable
      Handler: edu.uchicago.gerber.movies.ReadMoviesLambda::handleRequest
      Events:
        PostMovie:
          Type: Api
          Properties:
            Path: /movies
            Method: GET

Outputs:
  moviesApi:
    Description: "API Gateway endpoint for moviesApi"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/movies"
